### ISSUE TITLE
data corruption when sync to block number 2330000 using v11.0.7.

### ISSUE THREAD

**Issue by wangchengao** [tenet-org/tenet-mainnet#3]
I get a panic when sync to height 2330000.
![5c4d9d66-14c6-4549-95b8-775bfeebb9a4](https://github.com/tenet-org/tenet-mainnet/assets/16609371/ec2708da-5351-4e7c-ad95-e9a781615aec)
 And than upgrade my binaries to v11.2.0 but also has a panic 

```tenet  | 10:01AM INF Unlocking keyring
tenet  | 10:01AM INF starting ABCI with Tendermint
tenet  | 10:02AM INF starting node with ABCI Tendermint in-process
tenet  | 10:02AM INF service start impl=multiAppConn module=proxy msg={} server=node
tenet  | 10:02AM INF service start connection=query impl=localClient module=abci-client msg={} server=node
tenet  | 10:02AM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
tenet  | 10:02AM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
tenet  | 10:02AM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
tenet  | 10:02AM INF service start impl=EventBus module=events msg={} server=node
tenet  | 10:02AM INF service start impl=PubSub module=pubsub msg={} server=node
tenet  | 10:02AM INF service start impl=IndexerService module=txindex msg={} server=node
tenet  | 10:02AM INF ABCI Handshake App Info hash="N��\x7fOn�U����\x15ӛ��E��K\v\x1e���us\\\x1b�W" height=2329999 module=consensus protocol-version=0 server=node software-version=11.2.0
tenet  | 10:02AM INF ABCI Replay Blocks appHeight=2329999 module=consensus server=node stateHeight=0 storeHeight=0
tenet  | panic: state.AppHash does not match AppHash after replay. Got
tenet  | 4E88AE7F4F6E875595F4AF9315D39BA6BC4587B74B0B1E9AB8CC75735C1BDA57, expected .
tenet  |
tenet  | State: {{{11 0} 0.34.26} tenet_1559-1 1 0 :0:000000000000 2023-04-17 09:45:19.160552 +0000 UTC ValidatorSet{
tenet  |   Proposer: nil-Validator
tenet  |   Validators:
tenet  |
tenet  | } ValidatorSet{
tenet  |   Proposer: nil-Validator
tenet  |   Validators:
tenet  |
tenet  | } ValidatorSet{
tenet  |   Proposer: nil-Validator
tenet  |   Validators:
tenet  |
tenet  | } 1 {{22020096 20000000 1000} {100000 48h0m0s 1048576} {[ed25519]} {0}} 1 [] []}
tenet  |
tenet  | Did you reset Tendermint without resetting your application's data?
tenet  |
tenet  | goroutine 1 [running]:
tenet  | github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromState({_, _, _}, {{{0xb, 0x0}, {0x2940084, 0x7}}, {0xc003d36960, 0xc}, 0x1, ...})
tenet  | 	/root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:525 +0x179
tenet  | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2940084, 0x7}}, {0xc003d36960, 0xc}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
tenet  | 	/root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:361 +0x965
tenet  | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00264b240, {0x3745760, 0xc0018d4ea0})
tenet  | 	/root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:268 +0x3d4
tenet  | github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2940084, 0x7}}, {0xc003d36960, 0xc}, 0x1, 0x0, ...}, ...)
tenet  | 	/root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/node/node.go:329 +0x1b8
tenet  | github.com/tendermint/tendermint/node.NewNode(0xc0014c5cc0, {0x3729470, 0xc0014cd720}, 0xc001582660, {0x37080e0, 0xc003d32e10}, 0x1?, 0x4e86cc8?, 0xc001582880, {0x372f7e8, ...}, ...)
tenet  | 	/root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/node/node.go:777 +0x597
tenet  | github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3756060, 0xc0019fee10}, 0x0, {0xc000520c90, 0xc}, {0x374a158, ...}, ...}, ...)
tenet  | 	/root/go/pkg/mod/github.com/evmos/ethermint@v0.21.0/server/start.go:374 +0xf67
tenet  | github.com/evmos/ethermint/server.StartCmd.func2(0xc0018e8f00?, {0xc0019353e0?, 0x0?, 0x2?})
tenet  | 	/root/go/pkg/mod/github.com/evmos/ethermint@v0.21.0/server/start.go:158 +0x265
tenet  | github.com/spf13/cobra.(*Command).execute(0xc0018e8f00, {0xc0019353c0, 0x2, 0x2})
tenet  | 	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
tenet  | github.com/spf13/cobra.(*Command).ExecuteC(0xc0018b4900)
tenet  | 	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
tenet  | github.com/spf13/cobra.(*Command).Execute(...)
tenet  | 	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
tenet  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
tenet  | 	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
tenet  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x2381fa0?, {0x293fb8e, 0x6}, {0xc0010b2db0, 0xd})
tenet  | 	/root/go/pkg/mod/github.com/evmos/cosmos-sdk@v0.46.9-ledger/server/cmd/execute.go:36 +0x20f
tenet  | main.main()
tenet  | 	/go/src/github.com/tenet-org/tenet-chain/cmd/tenetd/main.go:36 +0x45
tenet exited with code 2 
```

it seems the panic in v11.0.7 corruption the chain data, and how can i repair chain data?

**Comment by danil-lashin** [comment]
Hey! 

Provided logs show that you did something unnecessary beside upgrading the binary to v11.2.0. For example, ran `tenetd tendermint unsafe-reset-all` which crashed whose database of your node. 

At this point it is not possible for you to recover from this situation. Please, try to resync your node again from scratch using v11.0.7 and then upgrading to v11.2.0 at block 2330000 (multichain upgrade height).

**Comment by wangchengao** [comment]
Hello,
    I apologize for the inconvenience caused by the unnecessary actions taken during the upgrade to v11.2.0.
but i not ran any cmd for the chain data. it seem cause by the panic for v11.0.7 in picture, and it make binary exit without graceful shutdown.
